#!/usr/bin/env python
import os
import sys

Program('embedded-boxer.c',
        CPPPATH=["/opt/homebrew/include"],
        LIBS=['libecl', 'libboxercore--all-systems'],
        LIBPATH=['./', '../', "/opt/homebrew/lib"]
)
